import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { PostsProvider } from "@/contexts/PostsContext";
import { AuthContextProvider } from "@/contexts/AuthContext";
import { ResponsiveAppBar } from "@/components/navbar/Navbar";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <AuthContextProvider>
                    <PostsProvider>
                        <div>
                            <ResponsiveAppBar />
                            {children}
                        </div>
                    </PostsProvider>
                </AuthContextProvider>
            </body>
        </html>
    );
}
