import type { Metadata } from "next";
import "./globals.css";
import { PostsProvider } from "@/contexts/PostsContext";
import { AuthContextProvider } from "@/contexts/AuthContext";
import { ResponsiveAppBar } from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";

import { AbstractIntlMessages, NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";
import { Locale, routing } from "@/i18n/routing";

export const metadata: Metadata = {
    title: "Polish Hema Federation",
    description: "Generated by create next app",
    icons: {
        icon: "/favicon.ico",
    },
};

export default async function RootLayout({
    children,
    params,
}: Readonly<{
    children: React.ReactNode;
    params: { locale: string };
}>) {
    const getParams = async () => params;
    const awaitParams = await getParams();
    const getLocale = async () => awaitParams.locale;
    const locale = await getLocale();

    if (!routing.locales.includes(locale as Locale)) {
        notFound();
    }

    const messages: AbstractIntlMessages = await import(
        `@/messages/${locale}.json`
    )
        .then((module) => module.default)
        .catch((error) => {
            console.error(
                `Error loading messages for locale: ${locale}`,
                error
            );
            return {};
        });
    return (
        <html lang={locale}>
            <head>
                <link rel="icon" href="/favicon.ico" sizes="any" />
                <link rel="icon" type="image/png" href="/favicon.png" />
                <meta
                    name="description"
                    content="The Polish HEMA Federation is a sports organization established to professionalize historical fencing in Poland. We organize the Polish HEMA League – a flagship, year-round tournament series that attracts the best of the best. We train referees, support and organize events related to historical reenactment and other tournaments, assist beginner clubs, and promote our sport and martial art."
                ></meta>
            </head>
            <body>
                <NextIntlClientProvider messages={messages}>
                    <AuthContextProvider>
                        <PostsProvider>
                            <div>
                                <ResponsiveAppBar />
                                {children}
                                <Footer />
                            </div>
                        </PostsProvider>
                    </AuthContextProvider>
                </NextIntlClientProvider>
            </body>
        </html>
    );
}
